### ISSUE TITLE
Undefined  index error  OmGateway.php

### ISSUE THREAD

**Issue by collisiondetection** [openmeetings/openmeetings-api-plugin#1]
When testing the file upload  I  receive  this error :

![image](https://user-images.githubusercontent.com/4151385/66697211-cfe0ad80-ecfd-11e9-8eac-c49e35c66f5d.png)

Line  44  in OmGateway.php  is : 

```
function __construct($cfg) {
		$this->config = $cfg;
		$this->debug = true === $cfg["debug"];   //  line  44
	}

```

**Comment by solomax** [comment]
So, I believe, you need to fill `debug` property in cfg :)
